# Generated by CMake - DO NOT EDIT MANUALLY
# To regenerate: cmake -B build && cmake --build build --target generate-makefile

CXX			:=	c++
CXXFLAGS	:=	-Wall -Wextra -Werror -std=c++98

NAME	:=	webserv
SOURCES	:=	main.cpp \
			BlockNode.cpp \
			Body.cpp \
			Config.cpp \
			Connection.cpp \
			DirectiveNode.cpp \
			EchoHandler.cpp \
			FileHandler.cpp \
			file_utils.cpp \
			Header.cpp \
			HttpMethod.cpp \
			HttpStatus.cpp \
			Location.cpp \
			Logger.cpp \
			Message.cpp \
			PostUploadHandler.cpp \
			Request.cpp \
			RequestLine.cpp \
			Response.cpp \
			Server.cpp \
			ServerManager.cpp \
			StatusLine.cpp \
			utils.cpp \
			RedirectHandler.cpp

OBJECTS	:=	$(patsubst %.cpp,%.o,$(SOURCES))
DEPENDS	:=	$(patsubst %.cpp,%.d,$(SOURCES))

# Files that, when changed, should trigger regenerating the Makefile
CMAKE_INPUTS := CMakeLists.txt generate_makefile.cmake Makefile.in
STAMP := build/.cmake_stamp

all: $(STAMP) $(NAME)

$(NAME): $(OBJECTS)
	$(CXX) $(CXXFLAGS) $^ -o $@

-include $(DEPENDS)

%.o: %.cpp Makefile
	$(CXX) $(CXXFLAGS) -MMD -MP -c $< -o $@

clean:
	$(RM) $(OBJECTS) $(DEPENDS)

fclean: clean
	$(RM) $(NAME) $(STAMP)

re: fclean
	@rm -f $(STAMP)
	$(MAKE) all

# Regenerate the auto-generated Makefile when CMake inputs change.
$(STAMP): $(CMAKE_INPUTS)
	@if command -v cmake >/dev/null 2>&1; then \
		cmake -B build && cmake --build build --target generate-makefile; \
		mkdir -p $(dir $@); \
		touch $@; \
	else \
		echo "Warning: CMake not found, skipping Makefile regeneration"; \
		mkdir -p $(dir $@); \
		touch $@; \
	fi

regenerate-stamp:
	@rm -f $(STAMP) && $(MAKE) $(STAMP)

regenerate: regenerate-stamp

.PHONY: all clean fclean re regenerate-stamp regenerate
