# Generated by CMake - DO NOT EDIT MANUALLY
# To regenerate: cmake -B build && cmake --build build --target generate-makefile

CXX			:=	c++
CXXFLAGS	:=	-Wall -Wextra -Werror -std=c++98

NAME	:=	webserv
SOURCES	:=	src/http/Body.cpp \
			src/http/Header.cpp \
			src/http/HttpMethod.cpp \
			src/http/HttpStatus.cpp \
			src/http/Message.cpp \
			src/http/Request.cpp \
			src/http/RequestLine.cpp \
			src/http/Response.cpp \
			src/http/StatusLine.cpp \
			src/utils/file_utils.cpp \
			src/utils/Logger.cpp \
			src/utils/utils.cpp \
			src/config/BlockNode.cpp \
			src/config/Config.cpp \
			src/config/DirectiveNode.cpp \
			src/config/Location.cpp \
			src/handlers/EchoHandler.cpp \
			src/handlers/FileHandler.cpp \
			src/handlers/RedirectHandler.cpp \
			src/core/Connection.cpp \
			src/core/Server.cpp \
			src/core/ServerManager.cpp

# Store object and dependency files under build/ to keep the source tree clean
OBJDIR := build/obj
DEPDIR := build/dep

# Default include paths so the generated Makefile can compile sources in-place
# (keeps `#include "Foo.hpp"` working when headers are next to sources)
INCLUDES := -I. -Isrc -Isrc/core -Isrc/http -Isrc/config -Isrc/utils -Isrc/handlers

OBJECTS	:=	$(patsubst %.cpp,$(OBJDIR)/%.o,$(SOURCES))
DEPENDS	:=	$(patsubst %.cpp,$(DEPDIR)/%.d,$(SOURCES))

# Directories to create before building so compilers can write .o/.d files safely
PREPARE_DIRS := $(sort $(dir $(OBJECTS)) $(dir $(DEPENDS)))

.PHONY: prepare
prepare:
	@mkdir -p $(PREPARE_DIRS)

# Files that, when changed, should trigger regenerating the Makefile
CMAKE_INPUTS := CMakeLists.txt cmake/generate_makefile.cmake cmake/Makefile.in
STAMP := build/.cmake_stamp

all: prepare $(STAMP) $(NAME)

$(NAME): $(OBJECTS)
	$(CXX) $(CXXFLAGS) $^ -o $@

-include $(DEPENDS)

$(OBJDIR)/%.o: %.cpp Makefile
	@dep=$(patsubst $(OBJDIR)/%.o,$(DEPDIR)/%.d,$@); \
	mkdir -p $(dir $@) $$(dir $$dep); \
	$(CXX) $(CXXFLAGS) $(INCLUDES) -MMD -MP -MF $$dep -c $< -o $@

clean:
	$(RM) $(OBJECTS) $(DEPENDS)
	@rm -rf $(OBJDIR) $(DEPDIR)

fclean: clean
	$(RM) $(NAME) $(STAMP)

re: fclean
	@rm -f $(STAMP)
	$(MAKE) all

test:
	@mkdir -p build
	@cmake -S . -B build
	@cmake --build build --target runTests -- -j
	@ctest --test-dir build --output-on-failure

clean-tests:
	@rm -rf build/Testing

# Regenerate the auto-generated Makefile when CMake inputs change.
$(STAMP): $(CMAKE_INPUTS)
	@if command -v cmake >/dev/null 2>&1; then \
		cmake -B build && cmake --build build --target generate-makefile; \
		mkdir -p $(dir $@); \
		touch $@; \
	else \
		echo "Warning: CMake not found, skipping Makefile regeneration"; \
		mkdir -p $(dir $@); \
		touch $@; \
	fi

regenerate-stamp:
	@rm -f $(STAMP) && $(MAKE) $(STAMP)

regenerate: regenerate-stamp

.PHONY: all clean fclean re test clean-tests regenerate-stamp regenerate
